# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mathieu/Git/Progetto-Tetris

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mathieu/Git/Progetto-Tetris

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mathieu/Git/Progetto-Tetris/CMakeFiles /home/mathieu/Git/Progetto-Tetris//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mathieu/Git/Progetto-Tetris/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tetris

# Build rule for target.
Tetris: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tetris
.PHONY : Tetris

# fast build rule for target.
Tetris/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/build
.PHONY : Tetris/fast

Giuoco.o: Giuoco.cpp.o
.PHONY : Giuoco.o

# target to build an object file
Giuoco.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Giuoco.cpp.o
.PHONY : Giuoco.cpp.o

Giuoco.i: Giuoco.cpp.i
.PHONY : Giuoco.i

# target to preprocess a source file
Giuoco.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Giuoco.cpp.i
.PHONY : Giuoco.cpp.i

Giuoco.s: Giuoco.cpp.s
.PHONY : Giuoco.s

# target to generate assembly for a file
Giuoco.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Giuoco.cpp.s
.PHONY : Giuoco.cpp.s

Griglia.o: Griglia.cpp.o
.PHONY : Griglia.o

# target to build an object file
Griglia.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Griglia.cpp.o
.PHONY : Griglia.cpp.o

Griglia.i: Griglia.cpp.i
.PHONY : Griglia.i

# target to preprocess a source file
Griglia.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Griglia.cpp.i
.PHONY : Griglia.cpp.i

Griglia.s: Griglia.cpp.s
.PHONY : Griglia.s

# target to generate assembly for a file
Griglia.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Griglia.cpp.s
.PHONY : Griglia.cpp.s

Linea.o: Linea.cpp.o
.PHONY : Linea.o

# target to build an object file
Linea.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Linea.cpp.o
.PHONY : Linea.cpp.o

Linea.i: Linea.cpp.i
.PHONY : Linea.i

# target to preprocess a source file
Linea.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Linea.cpp.i
.PHONY : Linea.cpp.i

Linea.s: Linea.cpp.s
.PHONY : Linea.s

# target to generate assembly for a file
Linea.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Linea.cpp.s
.PHONY : Linea.cpp.s

Quadrato.o: Quadrato.cpp.o
.PHONY : Quadrato.o

# target to build an object file
Quadrato.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Quadrato.cpp.o
.PHONY : Quadrato.cpp.o

Quadrato.i: Quadrato.cpp.i
.PHONY : Quadrato.i

# target to preprocess a source file
Quadrato.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Quadrato.cpp.i
.PHONY : Quadrato.cpp.i

Quadrato.s: Quadrato.cpp.s
.PHONY : Quadrato.s

# target to generate assembly for a file
Quadrato.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Quadrato.cpp.s
.PHONY : Quadrato.cpp.s

Tetramino.o: Tetramino.cpp.o
.PHONY : Tetramino.o

# target to build an object file
Tetramino.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Tetramino.cpp.o
.PHONY : Tetramino.cpp.o

Tetramino.i: Tetramino.cpp.i
.PHONY : Tetramino.i

# target to preprocess a source file
Tetramino.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Tetramino.cpp.i
.PHONY : Tetramino.cpp.i

Tetramino.s: Tetramino.cpp.s
.PHONY : Tetramino.s

# target to generate assembly for a file
Tetramino.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Tetramino.cpp.s
.PHONY : Tetramino.cpp.s

Title.o: Title.cpp.o
.PHONY : Title.o

# target to build an object file
Title.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Title.cpp.o
.PHONY : Title.cpp.o

Title.i: Title.cpp.i
.PHONY : Title.i

# target to preprocess a source file
Title.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Title.cpp.i
.PHONY : Title.cpp.i

Title.s: Title.cpp.s
.PHONY : Title.s

# target to generate assembly for a file
Title.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Title.cpp.s
.PHONY : Title.cpp.s

Window.o: Window.cpp.o
.PHONY : Window.o

# target to build an object file
Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Window.cpp.o
.PHONY : Window.cpp.o

Window.i: Window.cpp.i
.PHONY : Window.i

# target to preprocess a source file
Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Window.cpp.i
.PHONY : Window.cpp.i

Window.s: Window.cpp.s
.PHONY : Window.s

# target to generate assembly for a file
Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Window.cpp.s
.PHONY : Window.cpp.s

classifica.o: classifica.cpp.o
.PHONY : classifica.o

# target to build an object file
classifica.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/classifica.cpp.o
.PHONY : classifica.cpp.o

classifica.i: classifica.cpp.i
.PHONY : classifica.i

# target to preprocess a source file
classifica.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/classifica.cpp.i
.PHONY : classifica.cpp.i

classifica.s: classifica.cpp.s
.PHONY : classifica.s

# target to generate assembly for a file
classifica.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/classifica.cpp.s
.PHONY : classifica.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Tetris"
	@echo "... Giuoco.o"
	@echo "... Giuoco.i"
	@echo "... Giuoco.s"
	@echo "... Griglia.o"
	@echo "... Griglia.i"
	@echo "... Griglia.s"
	@echo "... Linea.o"
	@echo "... Linea.i"
	@echo "... Linea.s"
	@echo "... Quadrato.o"
	@echo "... Quadrato.i"
	@echo "... Quadrato.s"
	@echo "... Tetramino.o"
	@echo "... Tetramino.i"
	@echo "... Tetramino.s"
	@echo "... Title.o"
	@echo "... Title.i"
	@echo "... Title.s"
	@echo "... Window.o"
	@echo "... Window.i"
	@echo "... Window.s"
	@echo "... classifica.o"
	@echo "... classifica.i"
	@echo "... classifica.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

